services:
  # api:
  #   build: ./api
  #   container_name: api_c
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./api:/app
  #     - ./app/node_modules
  finance-project:
    build: .
    container_name: finance-project_c
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

